DROP TABLE IF EXISTS commentaire;
DROP TABLE IF EXISTS participant;
DROP TABLE IF EXISTS joueur;
DROP TABLE IF EXISTS rencontre;

CREATE TABLE joueur (
	id INT AUTO_INCREMENT PRIMARY KEY,
	numeroDeLicence INT UNIQUE,
	nom VARCHAR(20) NOT NULL,
	prenom VARCHAR(20) NOT NULL,
	dateDeNaissance DATE NOT NULL,
	taille INT NOT NULL,
	poids DECIMAL(4, 1) NOT NULL,
	statut ENUM('ACTIF', 'BLESSE', 'SUSPENDU', 'ABSENT') NOT NULL,
	poste ENUM('GARDIEN', 'DEFENSEUR', 'MILIEU', 'ATTAQUANT') NOT NULL
);

CREATE TABLE commentaire (
	id INT AUTO_INCREMENT PRIMARY KEY,
	idJoueur INT NOT NULL,
	note VARCHAR(500) NOT NULL
);

CREATE TABLE participant (
	id INT AUTO_INCREMENT PRIMARY KEY,
	idJoueur INT NOT NULL,
	idRencontre INT NOT NULL,
	typeDeParticipation ENUM('TITULAIRE', 'REMPLACANT') NOT NULL,
	poste ENUM('GARDIEN', 'DEFENSEUR', 'MILIEU', 'ATTAQUANT') NOT NULL,
	evaluation INT
);

CREATE TABLE rencontre (
	id INT AUTO_INCREMENT PRIMARY KEY,
	dateEtHeure DATETIME NOT NULL,
	lieu ENUM('DOMICILE', 'EXTERIEUR') NOT NULL,
	adresse VARCHAR(100) NOT NULL,
	nomEquipeAdverse VARCHAR(20) NOT NULL,
	resultat ENUM('VICTOIRE', 'DEFAITE', 'NUL'),
	scoreEquipeLocale INT,
	scoreEquipeAdverse INT
);